Parameters:
  CloudConfig:
    Description: Cloud config base64 string.
    Type: String

Resources:
  BMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-057b0e5f4e7564dab
      SecurityGroups:
        - black_metal
      InstanceType: t4g.nano
      KeyName: sharmuta
      UserData: !Ref CloudConfig
  BMDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: BMInstance
    Properties:
      DistributionConfig:
        Enabled: true
        IPV6Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt BMInstance.PublicDnsName
            Id: 123
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: 123
          ForwardedValues:
            QueryString: true
          ViewerProtocolPolicy: allow-all
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
          CachePolicyId: 83da9c7e-98b4-4e11-a168-04f0df8e2c65

Outputs:
  BMInstanceDNS:
    Description: Website URL
    Value: !GetAtt BMInstance.PublicDnsName
# hello2s
