Parameters:
  BMInstanceDnsName:
    Description: EC2 Instance DNS
    Type: String

Resources:
  BMDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        IPV6Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !Ref BMInstanceDnsName
            Id: 123
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: 123
          ForwardedValues:
            QueryString: true
          ViewerProtocolPolicy: allow-all
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
          CachePolicyId: 83da9c7e-98b4-4e11-a168-04f0df8e2c65
