name: initialize stack for other resources

on:
  workflow_dispatch:

jobs:
  initialize:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: deploy check if instance exists first
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          BM_INSTANCE_STACKS=$(aws cloudformation describe-stacks --stack-name bm-instance-stack --region \
          eu-north-1 | jq length)
          if [[ $BM_INSTANCE_STACKS == 1 ]] 
          then 
              echo "deploying infracture"
          else 
              echo "ec2 stack not created yet"
              exit 1
          fi
      - uses: actions/checkout@v3
      - name: initialize stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          BM_INSTANCE_DNS=$(aws cloudformation describe-stacks --stack-name bm-instance-stack \
          --query Stacks[0].Outputs -region eu-north-1 \
          | jq 'map(select(.OutputKey | contains("BMInstanceDNS")))' | jq first.OutputValue | sed "s/\"//g")
          gh secret set EC2_HOST --repo Koji-Sunioj/bm --body "$BM_INSTANCE_DNS"
          aws cloudformation create-stack --stack-name bm-infra-stack --template-body file://bm_infra_cfn.yaml \
          --parameters ParameterKey=BMInstanceDnsName,ParameterValue=$BM_INSTANCE_DNS \
          --output text --region eu-north-1
